// Code generated by protoc-gen-go.
// source: ConfigPayload.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	ConfigPayload.proto
	DataPayload.proto
	DevicePayload.proto
	StatusPayload.proto
	UDFPayload.proto
	UDMPayload.proto

It has these top-level messages:
	ConfigPayload
	ConfDevice
	ConfAttribute
	DataPayload
	Attribute
	ExecAttribute
	AttributeValue
	DevicePayload
	DeviceInfo
	StatusPayload
	StatDevice
	IOPoint
	UDFPayload
	UDMPayload
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ConfigPayload struct {
	CreatedAt        *int64                    `protobuf:"varint,1,opt,name=createdAt" json:"createdAt,omitempty"`
	ConfDevice       []*ConfDevice             `protobuf:"bytes,5000,rep,name=confDevice" json:"confDevice,omitempty"`
	ConfAttribute    []*ConfAttribute          `protobuf:"bytes,5001,rep,name=confAttribute" json:"confAttribute,omitempty"`
	ReqId            *int64                    `protobuf:"varint,5002,opt,name=reqId" json:"reqId,omitempty"`
	ReqTy            *int32                    `protobuf:"varint,5003,opt,name=reqTy,def=0" json:"reqTy,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ConfigPayload) Reset()                    { *m = ConfigPayload{} }
func (m *ConfigPayload) String() string            { return proto.CompactTextString(m) }
func (*ConfigPayload) ProtoMessage()               {}
func (*ConfigPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

var extRange_ConfigPayload = []proto.ExtensionRange{
	{2, 4999},
}

func (*ConfigPayload) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_ConfigPayload
}
func (m *ConfigPayload) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

const Default_ConfigPayload_ReqTy int32 = 0

func (m *ConfigPayload) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *ConfigPayload) GetConfDevice() []*ConfDevice {
	if m != nil {
		return m.ConfDevice
	}
	return nil
}

func (m *ConfigPayload) GetConfAttribute() []*ConfAttribute {
	if m != nil {
		return m.ConfAttribute
	}
	return nil
}

func (m *ConfigPayload) GetReqId() int64 {
	if m != nil && m.ReqId != nil {
		return *m.ReqId
	}
	return 0
}

func (m *ConfigPayload) GetReqTy() int32 {
	if m != nil && m.ReqTy != nil {
		return *m.ReqTy
	}
	return Default_ConfigPayload_ReqTy
}

type ConfDevice struct {
	DvcId              *int64                    `protobuf:"varint,1,opt,name=dvcId" json:"dvcId,omitempty"`
	FnctngModeCd       *int32                    `protobuf:"varint,2,opt,name=fnctngModeCd" json:"fnctngModeCd,omitempty"`
	TotalOpenExecTime  *int32                    `protobuf:"varint,3,opt,name=totalOpenExecTime" json:"totalOpenExecTime,omitempty"`
	TotalCloseExecTime *int32                    `protobuf:"varint,4,opt,name=totalCloseExecTime" json:"totalCloseExecTime,omitempty"`
	ExecOffsetTime     *int32                    `protobuf:"varint,5,opt,name=execOffsetTime" json:"execOffsetTime,omitempty"`
	XXX_extensions     map[int32]proto.Extension `json:"-"`
	XXX_unrecognized   []byte                    `json:"-"`
}

func (m *ConfDevice) Reset()                    { *m = ConfDevice{} }
func (m *ConfDevice) String() string            { return proto.CompactTextString(m) }
func (*ConfDevice) ProtoMessage()               {}
func (*ConfDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

var extRange_ConfDevice = []proto.ExtensionRange{
	{6, 999},
}

func (*ConfDevice) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_ConfDevice
}
func (m *ConfDevice) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *ConfDevice) GetDvcId() int64 {
	if m != nil && m.DvcId != nil {
		return *m.DvcId
	}
	return 0
}

func (m *ConfDevice) GetFnctngModeCd() int32 {
	if m != nil && m.FnctngModeCd != nil {
		return *m.FnctngModeCd
	}
	return 0
}

func (m *ConfDevice) GetTotalOpenExecTime() int32 {
	if m != nil && m.TotalOpenExecTime != nil {
		return *m.TotalOpenExecTime
	}
	return 0
}

func (m *ConfDevice) GetTotalCloseExecTime() int32 {
	if m != nil && m.TotalCloseExecTime != nil {
		return *m.TotalCloseExecTime
	}
	return 0
}

func (m *ConfDevice) GetExecOffsetTime() int32 {
	if m != nil && m.ExecOffsetTime != nil {
		return *m.ExecOffsetTime
	}
	return 0
}

type ConfAttribute struct {
	DvcId               *int64                    `protobuf:"varint,1,req,name=dvcId" json:"dvcId,omitempty"`
	AttrbCd             *int32                    `protobuf:"varint,2,req,name=attrbCd" json:"attrbCd,omitempty"`
	TransfCycleAttrbVal *int32                    `protobuf:"varint,3,opt,name=transfCycleAttrbVal" json:"transfCycleAttrbVal,omitempty"`
	XXX_extensions      map[int32]proto.Extension `json:"-"`
	XXX_unrecognized    []byte                    `json:"-"`
}

func (m *ConfAttribute) Reset()                    { *m = ConfAttribute{} }
func (m *ConfAttribute) String() string            { return proto.CompactTextString(m) }
func (*ConfAttribute) ProtoMessage()               {}
func (*ConfAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

var extRange_ConfAttribute = []proto.ExtensionRange{
	{4, 999},
}

func (*ConfAttribute) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_ConfAttribute
}
func (m *ConfAttribute) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *ConfAttribute) GetDvcId() int64 {
	if m != nil && m.DvcId != nil {
		return *m.DvcId
	}
	return 0
}

func (m *ConfAttribute) GetAttrbCd() int32 {
	if m != nil && m.AttrbCd != nil {
		return *m.AttrbCd
	}
	return 0
}

func (m *ConfAttribute) GetTransfCycleAttrbVal() int32 {
	if m != nil && m.TransfCycleAttrbVal != nil {
		return *m.TransfCycleAttrbVal
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigPayload)(nil), "ConfigPayload")
	proto.RegisterType((*ConfDevice)(nil), "ConfDevice")
	proto.RegisterType((*ConfAttribute)(nil), "ConfAttribute")
}

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xd3, 0x42, 0x45, 0x07, 0x21, 0xb8, 0x68, 0xb2, 0x07, 0x0f, 0xa4, 0x07, 0x21, 0xc6,
	0x10, 0x62, 0xe2, 0xc5, 0x1b, 0xa9, 0x1e, 0x3c, 0x18, 0x4c, 0x43, 0xbc, 0x2f, 0xbb, 0x53, 0xd2,
	0xa4, 0x76, 0xb1, 0xac, 0x04, 0xde, 0x00, 0xf5, 0xcd, 0xbc, 0xfa, 0x12, 0x3e, 0x86, 0xdb, 0x5d,
	0xa5, 0x54, 0xb9, 0x75, 0xbe, 0xf9, 0x66, 0xa6, 0x7f, 0x0b, 0xed, 0x40, 0xa6, 0x51, 0x3c, 0x7d,
	0x60, 0xab, 0x44, 0x32, 0xd1, 0x9f, 0x65, 0x52, 0x49, 0xff, 0xc3, 0x81, 0x46, 0x89, 0x93, 0x53,
	0x38, 0xe0, 0x19, 0x32, 0x85, 0x62, 0xa8, 0xa8, 0xd3, 0x71, 0x7a, 0x95, 0xb0, 0x00, 0xe4, 0x02,
	0x80, 0x6b, 0xfd, 0x06, 0x17, 0x31, 0x47, 0xba, 0xee, 0x76, 0x2a, 0xbd, 0xfa, 0x65, 0xbd, 0x1f,
	0x6c, 0x58, 0xb8, 0xd5, 0x27, 0x57, 0xd0, 0xc8, 0xab, 0xa1, 0x52, 0x59, 0x3c, 0x79, 0x51, 0x48,
	0x5f, 0xed, 0x40, 0xd3, 0x0c, 0x6c, 0x70, 0x58, 0xb6, 0xc8, 0x09, 0x78, 0x19, 0x3e, 0xdf, 0x09,
	0xfa, 0xd6, 0x35, 0xf7, 0x6d, 0x45, 0xa8, 0xc1, 0xe3, 0x15, 0x7d, 0xcf, 0xb1, 0x77, 0xed, 0x0c,
	0x42, 0x0b, 0xce, 0xbd, 0x7d, 0xb7, 0xb5, 0xee, 0xfa, 0x9f, 0x0e, 0x40, 0xf1, 0x26, 0xe4, 0x18,
	0x3c, 0xb1, 0xe0, 0x7a, 0x8d, 0x4d, 0x61, 0x0b, 0xe2, 0xc3, 0x61, 0x94, 0x72, 0x95, 0x4e, 0xef,
	0xa5, 0xc0, 0x40, 0x50, 0x37, 0xdf, 0x15, 0x96, 0x98, 0x4e, 0x79, 0xa4, 0xa4, 0x62, 0xc9, 0x68,
	0x86, 0xe9, 0xed, 0x12, 0xf9, 0x38, 0x7e, 0x42, 0x5a, 0x31, 0xe2, 0xff, 0x06, 0xe9, 0x03, 0x31,
	0x30, 0x48, 0xe4, 0x1c, 0x37, 0x7a, 0xd5, 0xe8, 0x3b, 0x3a, 0xe4, 0x0c, 0x9a, 0xa8, 0x9f, 0x47,
	0x51, 0x34, 0x47, 0x65, 0x5c, 0xcf, 0xb8, 0x7f, 0xa8, 0x4e, 0xb5, 0xd7, 0xfa, 0xaa, 0xf9, 0x4b,
	0xfb, 0x87, 0x8a, 0xcf, 0xb3, 0x95, 0xcb, 0x2d, 0x72, 0x51, 0xa8, 0x31, 0xad, 0x4c, 0x4c, 0x24,
	0x57, 0xaf, 0xfb, 0x2d, 0xc9, 0x00, 0xda, 0x2a, 0x63, 0xe9, 0x3c, 0x0a, 0x56, 0x3c, 0xc1, 0x7c,
	0xcf, 0xe4, 0x91, 0x25, 0x3f, 0x79, 0x76, 0xb5, 0xf4, 0xe5, 0xaa, 0xbe, 0xfc, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x0b, 0xf5, 0xce, 0x88, 0x32, 0x02, 0x00, 0x00,
}
