// Code generated by protoc-gen-go.
// source: UDFPayload.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UDFPayload struct {
	CreatedAt        *int64                    `protobuf:"varint,1,opt,name=createdAt" json:"createdAt,omitempty"`
	DvcId            *int64                    `protobuf:"varint,2,opt,name=dvcId" json:"dvcId,omitempty"`
	FnctTyCd         *int32                    `protobuf:"varint,3,req,name=fnctTyCd" json:"fnctTyCd,omitempty"`
	UdfNm            *string                   `protobuf:"bytes,101,opt,name=udfNm" json:"udfNm,omitempty"`
	UdfBody          *string                   `protobuf:"bytes,102,opt,name=udfBody" json:"udfBody,omitempty"`
	UdfTy            *string                   `protobuf:"bytes,103,opt,name=udfTy" json:"udfTy,omitempty"`
	StatCd           *int32                    `protobuf:"varint,104,opt,name=statCd" json:"statCd,omitempty"`
	StatMssage       *string                   `protobuf:"bytes,105,opt,name=statMssage" json:"statMssage,omitempty"`
	ReqId            *int64                    `protobuf:"varint,106,opt,name=reqId" json:"reqId,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *UDFPayload) Reset()                    { *m = UDFPayload{} }
func (m *UDFPayload) String() string            { return proto.CompactTextString(m) }
func (*UDFPayload) ProtoMessage()               {}
func (*UDFPayload) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

var extRange_UDFPayload = []proto.ExtensionRange{
	{4, 100},
}

func (*UDFPayload) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_UDFPayload
}
func (m *UDFPayload) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *UDFPayload) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *UDFPayload) GetDvcId() int64 {
	if m != nil && m.DvcId != nil {
		return *m.DvcId
	}
	return 0
}

func (m *UDFPayload) GetFnctTyCd() int32 {
	if m != nil && m.FnctTyCd != nil {
		return *m.FnctTyCd
	}
	return 0
}

func (m *UDFPayload) GetUdfNm() string {
	if m != nil && m.UdfNm != nil {
		return *m.UdfNm
	}
	return ""
}

func (m *UDFPayload) GetUdfBody() string {
	if m != nil && m.UdfBody != nil {
		return *m.UdfBody
	}
	return ""
}

func (m *UDFPayload) GetUdfTy() string {
	if m != nil && m.UdfTy != nil {
		return *m.UdfTy
	}
	return ""
}

func (m *UDFPayload) GetStatCd() int32 {
	if m != nil && m.StatCd != nil {
		return *m.StatCd
	}
	return 0
}

func (m *UDFPayload) GetStatMssage() string {
	if m != nil && m.StatMssage != nil {
		return *m.StatMssage
	}
	return ""
}

func (m *UDFPayload) GetReqId() int64 {
	if m != nil && m.ReqId != nil {
		return *m.ReqId
	}
	return 0
}

func init() {
	proto.RegisterType((*UDFPayload)(nil), "UDFPayload")
}

var fileDescriptor4 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x75, 0x71, 0x0b,
	0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xfa, 0xc6, 0xc8,
	0xc5, 0x85, 0x10, 0x14, 0x92, 0xe1, 0xe2, 0x4c, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x71, 0x2c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x42, 0x08, 0x08, 0x89, 0x70, 0xb1, 0xa6, 0x94, 0x25,
	0x7b, 0xa6, 0x48, 0x30, 0x81, 0x65, 0x20, 0x1c, 0x21, 0x29, 0x2e, 0x8e, 0xb4, 0xbc, 0xe4, 0x92,
	0x90, 0x4a, 0xe7, 0x14, 0x09, 0x66, 0x05, 0x26, 0x0d, 0xd6, 0x20, 0x38, 0x1f, 0xa4, 0xa3, 0x34,
	0x25, 0xcd, 0x2f, 0x57, 0x22, 0x15, 0xa8, 0x83, 0x33, 0x08, 0xc2, 0x11, 0x92, 0xe0, 0x62, 0x07,
	0x32, 0x9c, 0xf2, 0x53, 0x2a, 0x25, 0xd2, 0xc0, 0xe2, 0x30, 0x2e, 0x54, 0x7d, 0x48, 0xa5, 0x44,
	0x3a, 0x5c, 0x7d, 0x48, 0xa5, 0x90, 0x18, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x09, 0xd0, 0xfc, 0x0c,
	0xa0, 0x30, 0x6b, 0x10, 0x94, 0x27, 0x24, 0xc7, 0xc5, 0x05, 0x62, 0xf9, 0x16, 0x17, 0x27, 0xa6,
	0xa7, 0x4a, 0x64, 0x82, 0xb5, 0x20, 0x89, 0x80, 0x4c, 0x2b, 0x4a, 0x2d, 0x04, 0xba, 0x37, 0x0b,
	0xe2, 0x5e, 0x30, 0x47, 0x8b, 0x85, 0x83, 0x45, 0x20, 0xd5, 0x89, 0x2b, 0x8a, 0x03, 0x1c, 0x02,
	0x49, 0xa5, 0x69, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xc9, 0x14, 0x3d, 0x17, 0x01, 0x00,
	0x00,
}
