// Code generated by protoc-gen-go.
// source: UDMPayload.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UDMPayload struct {
	CreatedAt        *int64                    `protobuf:"varint,1,opt,name=createdAt" json:"createdAt,omitempty"`
	DvcId            *int64                    `protobuf:"varint,2,req,name=dvcId" json:"dvcId,omitempty"`
	MssageTyCd       *int32                    `protobuf:"varint,3,req,name=mssageTyCd" json:"mssageTyCd,omitempty"`
	UdmNm            *string                   `protobuf:"bytes,101,opt,name=udmNm" json:"udmNm,omitempty"`
	UdmBody          *string                   `protobuf:"bytes,102,opt,name=udmBody" json:"udmBody,omitempty"`
	UdmTy            *string                   `protobuf:"bytes,103,opt,name=udmTy" json:"udmTy,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *UDMPayload) Reset()                    { *m = UDMPayload{} }
func (m *UDMPayload) String() string            { return proto.CompactTextString(m) }
func (*UDMPayload) ProtoMessage()               {}
func (*UDMPayload) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

var extRange_UDMPayload = []proto.ExtensionRange{
	{4, 100},
}

func (*UDMPayload) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_UDMPayload
}
func (m *UDMPayload) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *UDMPayload) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *UDMPayload) GetDvcId() int64 {
	if m != nil && m.DvcId != nil {
		return *m.DvcId
	}
	return 0
}

func (m *UDMPayload) GetMssageTyCd() int32 {
	if m != nil && m.MssageTyCd != nil {
		return *m.MssageTyCd
	}
	return 0
}

func (m *UDMPayload) GetUdmNm() string {
	if m != nil && m.UdmNm != nil {
		return *m.UdmNm
	}
	return ""
}

func (m *UDMPayload) GetUdmBody() string {
	if m != nil && m.UdmBody != nil {
		return *m.UdmBody
	}
	return ""
}

func (m *UDMPayload) GetUdmTy() string {
	if m != nil && m.UdmTy != nil {
		return *m.UdmTy
	}
	return ""
}

func init() {
	proto.RegisterType((*UDMPayload)(nil), "UDMPayload")
}

var fileDescriptor5 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x75, 0xf1, 0x0d,
	0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x5a, 0xc3, 0xc8,
	0xc5, 0x85, 0x10, 0x14, 0x92, 0xe1, 0xe2, 0x4c, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x71, 0x2c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x42, 0x08, 0x08, 0x89, 0x70, 0xb1, 0xa6, 0x94, 0x25,
	0x7b, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x01, 0x65, 0x20, 0x1c, 0x21, 0x39, 0x2e, 0xae, 0xdc, 0xe2,
	0xe2, 0xc4, 0xf4, 0xd4, 0x90, 0x4a, 0xe7, 0x14, 0x09, 0x66, 0xa0, 0x14, 0x6b, 0x10, 0x92, 0x08,
	0x48, 0x57, 0x69, 0x4a, 0xae, 0x5f, 0xae, 0x44, 0x2a, 0xd0, 0x3c, 0xce, 0x20, 0x08, 0x47, 0x48,
	0x82, 0x8b, 0x1d, 0xc8, 0x70, 0xca, 0x4f, 0xa9, 0x94, 0x48, 0x03, 0x8b, 0xc3, 0xb8, 0x50, 0xf5,
	0x21, 0x95, 0x12, 0xe9, 0x70, 0xf5, 0x21, 0x95, 0x5a, 0x2c, 0x1c, 0x2c, 0x02, 0xa9, 0x4e, 0x5c,
	0x51, 0x1c, 0x60, 0x77, 0x27, 0x95, 0xa6, 0x01, 0x02, 0x00, 0x00, 0xff, 0xff, 0x32, 0xad, 0x3b,
	0xde, 0xcd, 0x00, 0x00, 0x00,
}
